from CheckmarxPythonSDK.CxAST import get_groups


def test_get_groups():
    response = get_groups()
    assert response is not None
    # 'HttpStatusCode: 403', 'ErrorMessage: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size="1px">\nRequest blocked.\nWe can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear="all">\n<HR noshade size="1px">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: IxZB6OIeEdQOiS4VK3VAFlkPyG8uC4Ou-MKwzymIoKs2vbkANyOoEQ==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>')