import http
OK = http.HTTPStatus.OK
BAD_REQUEST = http.HTTPStatus.BAD_REQUEST
NOT_FOUND = http.HTTPStatus.NOT_FOUND
UNAUTHORIZED = http.HTTPStatus.UNAUTHORIZED
CREATED = http.HTTPStatus.CREATED
FORBIDDEN = http.HTTPStatus.FORBIDDEN
NO_CONTENT = http.HTTPStatus.NO_CONTENT
ACCEPTED = http.HTTPStatus.ACCEPTED
CONFLICT = http.HTTPStatus.CONFLICT
