from dataclasses import dataclass


@dataclass
class FileChange:
    """A source code change generated by the remediation."""

    file_path: str = None
    analysis: str = None
    diff: str = None

    @classmethod
    def from_dict(cls, item: dict) -> "FileChange":
        return cls(
            file_path=item.get("file_path"),
            analysis=item.get("analysis"),
            diff=item.get("diff"),
        )
