openapi: 3.0.2
info:
  title: Custom States API
  description: These APIs are used to get list of custom states, create new or delete custom state
  version: 1.0.0
paths:
  "/":
    get:
      tags:
        - custom_states
      parameters:
        - $ref: "#/components/parameters/auth"
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/version"
        - in: query
          name: include-deleted
          schema:
            type: boolean
            default: false
          required: false
          description: If the parameter is specified and true, the response will contain all custom states including those marked as deleted. Otherwise only active Custom States will be returned.
      summary: Get custom states list
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomState"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - custom_states
      parameters:
        - $ref: "#/components/parameters/auth"
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/version"
      summary: Create new custom state
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: name of new custom state
      responses:
        "201":
          description: Successful operation
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
  "/{id}":
    delete:
      tags:
        - custom_states
      parameters:
        - $ref: "#/components/parameters/auth"
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/version"
        - name: id
          in: path
          required: true
          description: Custom State ID
          schema:
            type: string
      summary: Delete custom state
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  parameters:
    auth:
      in: header
      name: Authorization
      description: "JWT access token (REQUIRED)"
      schema:
        type: string
        format: JWT
    correlationId:
      in: header
      name: CorrelationId
      required: false
      description: "Correlation ID, used to keep track of a flow if many APIs are involved"
      schema:
        type: string
        format: uuid
    version:
      in: header
      name: Accept
      required: false
      description: "API version should be appended to this header"
      schema:
        type: string
        example: "*/*; version=1.0"
        pattern: .*version\s*=\s*([\d|.]+)
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebError"
    Unauthorized:
      description: Unauthorized, access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebError"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebError"
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebError"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebError"
  schemas:
    WebError:
      type: object
      properties:
        code:
          type: integer
          format: integer
        message:
          type: string
        data:
          type: object
    CustomState:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        isAllowed:
          type: boolean
  securitySchemes:
    Login:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /spec/cxauth.html
          scopes: {}
servers:
  - url: /api/custom-states
security:
  - Login: []
