openapi: 3.0.2
info:
  title: Preset Management Generic API
  version: 1.0.0
paths:
  "/{scanner}/presets":
    get:
      tags:
        - Presets
      summary: List presets
      parameters:
        - $ref: '#/components/parameters/Scanner'
        - in: query
          name: limit
          required: false
          example: 0
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - in: query
          name: offset
          required: false
          example: 25
          schema:
            type: integer
            minimum: 0
            default: 0
        - in: query
          name: fields
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: sort
          required: false
          example: "-description"
          schema:
            type: string
          description: "Sort the elements by a given column ascending (e.g.: description) or descending (eg.: -description)"
        - in: query
          name: include-details
          required: false
          example: false
          schema:
            type: boolean
            default: false
        - $ref: "#/components/parameters/SearchTerm"
        - in: query
          name: exact-match
          required: false
          example: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                $ref: "#/components/schemas/PresetPaged"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    post:
      parameters:
        - $ref: '#/components/parameters/Scanner'
      tags:
        - Presets
      summary: Create a new preset
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WritePreset"
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                $ref: "#/components/schemas/PresetOK"
        "400":
          description: The name or id of the preset is invalid, or trying to update a system preset
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"
  "/{scanner}/presets/{id}":
    get:
      tags:
        - Presets
      summary: Get preset by ID
      parameters:
        - $ref: '#/components/parameters/Scanner'
        - $ref: '#/components/parameters/PresetId'
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                $ref: "#/components/schemas/PresetDetails"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    put:
      tags:
        - Presets
      summary: Updates a preset
      parameters:
        - $ref: '#/components/parameters/Scanner'
        - $ref: '#/components/parameters/PresetId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WritePreset"
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                $ref: "#/components/schemas/PresetOK"
        "400":
          description: The name or id of the preset is invalid, or trying to update a system preset
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    delete:
      tags:
        - Presets
      summary: Delete a preset by ID
      parameters:
        - $ref: '#/components/parameters/Scanner'
        - $ref: '#/components/parameters/PresetId'
      responses:
        "200":
          description: Preset was deleted
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  "/{scanner}/presets/{id}/clone":
    post:
      tags:
        - Presets
      summary: Clone preset
      parameters:
        - $ref: '#/components/parameters/Scanner'
        - $ref: '#/components/parameters/PresetId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PresetClone"
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                $ref: "#/components/schemas/PresetOK"
        "400":
          description: The name or id of the preset is invalid, or trying to update a system preset
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  "/{scanner}/query-families":
    get:
      tags:
        - Queries
      summary: List the available query families
      parameters:
        - $ref: "#/components/parameters/Scanner"
        - $ref: "#/components/parameters/SearchTerm"
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                type: array
                items:
                  type: string
              examples:
                getQueryFamilies:
                  $ref: "#/components/examples/getQueryFamilies_200"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"
  "/{scanner}/query-families/{query-family}/queries":
    get:
      tags:
        - Queries
      summary: List the queries of a given family
      parameters:
        - $ref: "#/components/parameters/Scanner"
        - $ref: "#/components/parameters/SearchTerm"
        - in: path
          required: true
          name: query-family
          example: "Apex"
          schema:
            type: string
          description: "The name of the query family"
      responses:
        "200":
          description: OK
          content:
            application/json; version=1.0:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QueriesTree"
              examples:
                getAllQueries:
                  $ref: "#/components/examples/getAllQueries_200"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"
components:
  parameters:
    PresetId:
      in: path
      required: true
      name: id
      example: 1234
      schema:
        type: integer
    Scanner:
      in: path
      required: true
      name: scanner
      example: sast
      schema:
        type: string
        enum: ["sast", "iac"]
      description: "Scanner to use"
    SearchTerm:
      in: query
      name: search-term
      example: "name"
      schema:
        type: string
      required: false
      description: "The search term is used to filter the response. By default, an exact match is not required. This search also applies to query properties within each family, such as CWE and query name."
  responses:
    "401":
      description: "Unauthorized, Access token is missing or invalid"
    "403":
      description: "Forbidden"
    "404":
      description: "Not Found"
      content:
        application/json; version=1.0:
          schema:
            $ref: "#/components/schemas/Error"
    "400":
      description: "Bad Request"
      content:
        application/json; version=1.0:
          schema:
            $ref: "#/components/schemas/Error"
    "200":
      description: "Preset created/updated"
    "500":
      description: "Internal Server Error"
      content:
        application/json; version=1.0:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    WritePreset:
      type: object
      properties:
        name:
          type: string
          example: "High only"
          pattern: "^[A-Za-z0-9\\s\\-\\_]*$"
          maxLength: 30
        description:
          type: string
          example: "Queries with high severity only"
        queries:
          type: array
          items:
            $ref: "#/components/schemas/QueriesByFamily"
    PresetPaged:
      type: object
      properties:
        totalFilteredCount:
          type: integer
          example: 100
        totalCount:
          type: integer
          example: 100
        presets:
          type: array
          items:
            $ref: "#/components/schemas/PresetSummary"
    PresetSummary:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "High only"
          pattern: "^[A-Za-z0-9\\s\\-\\_]*$"
          maxLength: 30
          nullable: true
        description:
          type: string
          example: "Queries with high severity only"
          maxLength: 60
          nullable: true
        associatedProjects:
          type: integer
          example: 10
          nullable: true
        custom:
          type: boolean
          example: true
          nullable: true
        isTenantDefault:
          type: boolean
          example: true
          nullable: true
        isMigrated:
          type: boolean
          example: false
          nullable: true
    PresetClone:
      type: object
      properties:
        name:
          type: string
          example: "High only"
          pattern: "^[A-Za-z0-9\\s\\-\\_]*$"
          maxLength: 30
        description:
          type: string
          example: "Queries with high severity only"
          maxLength: 60
    PresetOK:
      type: object
      properties:
        id:
          type: integer
          example: 123456
        message:
          type: string
          example: "preset saved"
    QueriesTree:
      type: object
      properties:
        isLeaf:
          type: boolean
          example: false
        title:
          type: string
          example: CSharp_High_Risk
        key:
          type: string
          example: CSharp_High_Risk
        children:
          type: array
          items:
            $ref: "#/components/schemas/QueriesTree"
        data:
          type: object
          items:
            $ref: "#/components/schemas/QueryData"
    PresetDetails:
      type: object
      properties:
        id:
          type: string
          example: "123456"
        name:
          type: string
          example: "High only"
          pattern: "^[A-Za-z0-9\\s\\-\\_]*$"
          maxLength: 30
        description:
          type: string
          example: "Queries with high severity only"
        custom:
          type: boolean
          example: true
        queries:
          type: array
          items:
            $ref: "#/components/schemas/QueriesByFamily"
    QueriesByFamily:
      type: object
      properties:
        familyName:
          type: string
          example: "Apex"
        totalCount:
          type: integer
          example: 2
        queryIds:
          type: array
          items:
            type: string
          example: ["123", "456"]
    Error:
      type: object
      properties:
        code:
          type: integer
          format: integer
        message:
          type: string
        data:
          type: object
    QueryData:
      type: object
      properties:
        cwe:
          type: integer
          example: 123456
        custom:
          type: boolean
          example: true
        queryDescriptionId:
          type: integer
          example: 123456
        severity:
          type: string
          example: "High"
        url:
          type: string
          example: "https://docs.kics.io/2.1.6/queries/dockerfile-queries/67fd0c4a-68cf-46d7-8c41-bc9fba7e40ae/"
    PresetQuery:
      type: object
      properties:
        queryPath:
          type: string
          example: "queries/Java/Java_High_Risk/Sql_injection/Sql_Injection.cs"
  examples:
    getQueryFamilies_200:
      summary: Get All Query Families (Code 200)
      description: An example for getting Query Families Endpoint.
      value: ["Apex", "Cobol", "CPP", "CSharp", "Go", "Java"]
    getAllQueries_200:
      summary: Get All Queries (Code 200)
      description: An example for getting All Queries Endpoint.
      value:
        - isLeaf: false
          title: "Checkmarx predefined"
          key: "cx"
          data: null
          children:
            - isLeaf: false
              title: "Apex_High_Risk"
              key: "Cx-Apex_High_Risk"
              data: null
              children:
                - isLeaf: true
                  title: "Command_Injection"
                  key: "1"
                  data:
                    cwe: 123456
                    severity: "High"
                    queryDescriptionId: 123456
                    custom: false
                  children: []
                - isLeaf: true
                  title: "Reflected_XSS"
                  key: "2"
                  data:
                    cwe: 654321
                    severity: "High"
                    queryDescriptionId: 654321
                    custom: false
                  children: []
        - isLeaf: false
          title: "Custom"
          key: "custom"
          data: null
          children:
            - isLeaf: false
              title: "Apex_High_Risk"
              key: "Custom-Apex_High_Risk"
              data: null
              children:
                - isLeaf: true
                  title: "New_Query"
                  key: "1"
                  data:
                    cwe: 987654
                    severity: "Critical"
                    queryDescriptionId: 987654
                    custom: true
                  children: []
  securitySchemes:
    Login:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /spec/cxauth.html
          scopes: {}
servers:
  - url: /api/preset-manager
security:
  - Login: []
