openapi: 3.0.2
info:
  title: Sast Resource Management Service
  version: 1.0.0
paths:
  "/scans/{id}":
    get:
      tags:
        - Scans
      summary: Get a scan allocation info.
      parameters:
        - $ref: '#/components/parameters/auth'
        - $ref: '#/components/parameters/correlationId'
        - $ref: '#/components/parameters/version'
        - name: id
          in: path
          description: Scan Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scan'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
    delete:
      tags:
        - Scans
      summary: Forces scan execution to fail.
      parameters:
        - $ref: '#/components/parameters/auth'
        - $ref: '#/components/parameters/correlationId'
        - $ref: '#/components/parameters/version'
        - name: id
          in: path
          description: Scan Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
  "/scans":
    get:
      tags:
        - Scans
      summary: Get a list of scans
      parameters:
        - $ref: '#/components/parameters/auth'
        - $ref: '#/components/parameters/correlationId'
        - $ref: '#/components/parameters/version'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - name: ids
          in: query
          schema:
            type: array
            items:
              type: string
              format: uuid
          description: Ids of scans to return.
        - name: with-deleted
          in: query
          schema:
            type: boolean
          description: If deleted scans should be included in result.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scansCollection'
        '400':
          $ref: '#/components/responses/400'
components:
  parameters:
    auth:
      in: header
      name: Authorization
      description: "REQUIRED: JWT authorization token"
      schema:
        type: string
        format: JWT
    correlationId:
      in: header
      name: CorrelationId
      required: false
      description: "correlation id to keep track of a flow if many APIs are involved"
      schema:
        type: string
        format: uuid
    version:
      in: header
      name: Accept
      required: false
      description: "API version should be appended to this header"
      schema:
        type: string
        example: "*/*; version=1.0"
        pattern: .*version\s*=\s*([\d|.]+)
    offset:
      name: offset
      in: query
      schema:
        type: integer
        minimum: 0
        default: 0
        example: 0
      description: The number of items to skip before starting to collect the result set.
    limit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 0
        default: 20
        example: 20
      description: The number of items to return.
  schemas:
    scan:
      properties:
        id:
          type: string
          format: uuid
          description: "Scan id."
        state:
          $ref: '#/components/schemas/scanState'
        queuedAt:
          type: string
          format: 'date-time'
        allocatedAt:
          type: string
          format: 'date-time'
        runningAt:
          type: string
          format: 'date-time'
        engine:
          type: string
          format: uuid
        properties:
          type: array
          items:
            $ref: '#/components/schemas/property'
          description: "Scan allocation properties"
    scansCollection:
      type: object
      properties:
        totalCount:
          type: integer
          description: The number of records matching the applied filter.
        scans:
          type: array
          description: Scans of that specific group.
          items:
            $ref: '#/components/schemas/scan'
    scanState:
      type: string
      enum: ["Queued", "Allocated", "Running"]
      description: "Scan allocation state."
    property:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    tags:
      type: object
      additionalProperties:
        type: string
      example:
        tagOne: tagValue
        otherTag: other-tag value
    id:
      type: string
      format: uuid
    error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
        details:
          type: array
          items:
            type: string
  responses:
    '204':
      description: No Content
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    '401':
      description: Unauthorized
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    Login:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /spec/cxauth.html
          scopes: {}
servers:
  - url: /api/sast-rm
security:
  - Login: []
