openapi: 3.0.1
info:
  contact: {}
  title: SSCS API - Correlator
  version: "1.0"
paths:
  /predicates:
    post:
      operationId: HandlePostPredicates
      requestBody:
        content:
          '*/*':
            schema:
              items:
                $ref: '#/components/schemas/BasePredicate'
              type: array
        description: List of predicates to change
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                type: string
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      x-codegen-request-body-name: predicates
components:
  schemas:
    BasePredicate:
      example:
        severity: HIGH
        scanId: string
        comment: string
        state: TO_VERIFY
        projectId: string
        similarityId: string
        microengine: string
      properties:
        comment:
          example: string
          maxLength: 1024
          type: string
        microengine:
          example: string
          type: string
        projectId:
          example: string
          type: string
        scanId:
          example: string
          type: string
        severity:
          example: HIGH
          type: string
        similarityId:
          example: string
          type: string
        state:
          example: TO_VERIFY
          type: string
      required:
        - projectId
        - severity
        - similarityId
        - state
      type: object
    Error:
      example:
        code: 0
        message: message
        type: type
      properties:
        code:
          type: integer
        message:
          type: string
        type:
          type: string
      type: object
  securitySchemes:
    Login:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /spec/cxauth.html
          scopes: {}
x-original-swagger-version: "2.0"
servers:
  - url: /api/micro-engines/write/
security:
  - Login: []
