name: Checkmarx Scan
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  execute-scan:
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - name: Setup Python Build Env
        run: |
          pip config set global.index-url https://pypi.echohq.com/simple
          pip install virtualenv

      - name: Scan with CxOne++ Action
        id: cxscan
        uses: checkmarx-ts/cxone-plusplus-github-action@c922a363fd998c18521cc308eba96e7341ff6018 # v3
        with:
          cx-tenant: ${{ secrets.CXONE_TENANT }}
          cx-client-id: ${{ secrets.CXONE_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CXONE_CLIENT_SECRET }}
          upload-sarif-file: false
